apiVersion: v1
kind: ServiceAccount
metadata:
  name: genesis-updater
  namespace: indy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-updater
  namespace: indy
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: genesis-updater-binding
  namespace: indy
subjects:
- kind: ServiceAccount
  name: genesis-updater
  namespace: indy
roleRef:
  kind: Role
  name: configmap-updater
  apiGroup: rbac.authorization.k8s.io