apiVersion: v1
kind: Service
metadata:
  name: indy-pool
  namespace: indy
  labels:
    app: indy-node
spec:
  clusterIP: None 
  ports:
  - port: 9701
    name: node-port
  - port: 9702
    name: client-port
  selector:
    app: indy-node